### ISSUE TITLE
JVM Deadlock

### ISSUE THREAD

**Issue by alexkonti** [opentelecoms-org/jsmpp#60] opened 2017-01-08 10:48 UTC
At random times we get deadlocks. The jstack is showing this:

"pool-15-thread-4":
  waiting to lock Monitor@0x00007fd4cc0bc4b8 (Object@0x000000044b81fc90, a mobi/coolsigns/sms/proxy/service/gateway/embedded/smpp/session/SMPPSessionCustom),
  which is held by "PDUReaderWorker: mobi.coolsigns.sms.proxy.service.gateway.embedded.smpp.session.SMPPSessionCustom@454fd63"
"PDUReaderWorker: mobi.coolsigns.sms.proxy.service.gateway.embedded.smpp.session.SMPPSessionCustom@454fd63":
 waiting for ownable synchronizer 0x000000042de26f70, (a java/util/concurrent/locks/ReentrantLock$NonfairSync),
 which is held by "pool-15-thread-4"

The SMPPSessionCustom is nothing fancy just an extension of the original Class that returns the SMPPResultResp and not only the Id. 

`public class SMPPSessionCustom extends SMPPSession {
	private static final AtomicReference<Long> currentTime = new AtomicReference<>(System.currentTimeMillis());

	private final ConnectionProperties connectionProperties;
	private final int timeout;
	private final long id;

	public SMPPSessionCustom(ConnectionProperties connectionProperties) {
		super();
		this.connectionProperties = connectionProperties;
		this.timeout = this.connectionProperties.get(ConnectionConstants.OPERATOR_SUMBIT_SM_TIMEOUT, 35000);
		this.id = currentTime.accumulateAndGet(System.currentTimeMillis(),
				(prev, next) -> next > prev ? next : prev + 1);
	}

	public SMPPSessionCustom(PDUSender pduSender, PDUReader pduReader, ConnectionFactory connFactory,
			ConnectionProperties connectionProperties) {
		super(pduSender, pduReader, connFactory);
		this.connectionProperties = connectionProperties;
		this.timeout = this.connectionProperties.get(ConnectionConstants.OPERATOR_SUMBIT_SM_TIMEOUT, 35000);
		this.id = currentTime.accumulateAndGet(System.currentTimeMillis(),
				(prev, next) -> next > prev ? next : prev + 1);
	}

	public SMPPSessionCustom(String host, int port, BindParameter bindParam, PDUSender pduSender, PDUReader pduReader,
			ConnectionFactory connFactory, ConnectionProperties connectionProperties) throws IOException {
		super(host, port, bindParam, pduSender, pduReader, connFactory);
		this.connectionProperties = connectionProperties;
		this.timeout = this.connectionProperties.get(ConnectionConstants.OPERATOR_SUMBIT_SM_TIMEOUT, 35000);
		this.id = currentTime.accumulateAndGet(System.currentTimeMillis(),
				(prev, next) -> next > prev ? next : prev + 1);

	}

	public SMPPSessionCustom(String host, int port, BindParameter bindParam, ConnectionProperties connectionProperties)
			throws IOException {
		super(host, port, bindParam);
		this.connectionProperties = connectionProperties;
		this.timeout = this.connectionProperties.get(ConnectionConstants.OPERATOR_SUMBIT_SM_TIMEOUT, 35000);
		this.id = currentTime.accumulateAndGet(System.currentTimeMillis(),
				(prev, next) -> next > prev ? next : prev + 1);

	}

	public SubmitSmResp submitShortMessageGetResp(String serviceType, TypeOfNumber sourceAddrTon,
			NumberingPlanIndicator sourceAddrNpi, String sourceAddr, TypeOfNumber destAddrTon,
			NumberingPlanIndicator destAddrNpi, String destinationAddr, ESMClass esmClass, byte protocolId,
			byte priorityFlag, String scheduleDeliveryTime, String validityPeriod,
			RegisteredDelivery registeredDelivery, byte replaceIfPresentFlag, DataCoding dataCoding,
			byte smDefaultMsgId, byte[] shortMessage, OptionalParameter... optionalParameters) throws PDUException,
			ResponseTimeoutException, InvalidResponseException, NegativeResponseException, IOException {

		ensureTransmittable("submitShortMessage");

		SubmitSmCommandTask submitSmTask = new SubmitSmCommandTask(pduSender(), serviceType, sourceAddrTon,
				sourceAddrNpi, sourceAddr, destAddrTon, destAddrNpi, destinationAddr, esmClass, protocolId,
				priorityFlag, scheduleDeliveryTime, validityPeriod, registeredDelivery, replaceIfPresentFlag,
				dataCoding, smDefaultMsgId, shortMessage, optionalParameters);

		SubmitSmResp resp = (SubmitSmResp) executeSendCommand(submitSmTask, timeout);
		return resp;
	}

	public long getId() {
		return id;
	}

    }`

It affected both the last and the previous releases of JSMPP. Have not tried with previous ones lately. When I was using the 0.2.2 did not have this but i have not confirmed lately.

**Comment by pmoerenhout** [comment] 2017-01-15 16:57
I created a sample project, using this SMPPSessionCustom code, in https://github.com/pmoerenhout/jsmpp-sample-spring-boot. It creates a server and concurrent connect clients to it, sending concurrent messages in the session. I could not reproduce this deadlock. Could you provide some more info?

**Comment by alexkonti** [comment] 2017-01-16 11:24
Hi,

I should have given more context. We have faced the problem only with one SMSC. We are having 200 TPS allowed there and each message we are sending to the SMSC it get special handling which is very time consuming. As a result a lot of timeouts take place, even for enquire links, and as a result we are having a lot of diconnections (more than 4 per hour).

Based on the code of the example we are doing auto reconnects.

At some point in random times we are seeing outgoing on the account being frozen and the JStack is giving this dead lock indication. I suspect it has to do with the constant reconnects OR with the fact that timeouts are set very high (over 36 seconds) due to the traffic the other end has. 

Furthermore, the SMSC in case that they cannot process the SMS for some reason (e.g. the msisdn is purged from their subscriber list) they will throw a custom error code (which the library is handling as NegativeResponseException). We are talking about millions of cases like that.

Again I am not sure if the above are relevant to the error but I submit them for greater context.

**Comment by pmoerenhout** [comment] 2017-01-16 16:08
Thanks, I will try to simulate this scenario. Can you show how the reconnect logic is implemented ?

**Comment by alexkonti** [comment] 2017-01-16 18:22
private void reconnectAfter(final long timeInMillis) {

		final Runnable r = new Runnable() {
			int attempt = 0;
			int sleep = 1;

			public void run() {

				try {
					rlock.lockInterruptibly();
					sessionBounder.acquire();
					if (activeSessions.isMaximumConnectedReached(numberOfSessions)) {
						CONN_LOGGER.warn("ActiveSessions [{}] have a size [{}] so no more retries", operatorName, activeSessions.size());
						return;
					} else {
						CONN_LOGGER.info("Reconnecting attempt {} for operator [{}] with current active sessions [{}]...", ++attempt,
								operatorName, activeSessions.size());
						final SMPPSessionCustom session = createNewSmppSession();

						if (session.getSessionState().isBound()) {
							activeSessions.add(session);
							CONN_LOGGER.info("Reconnected session [{}] to [{}:{}] for operator [{}]. Active Sessions [{}]",
									session.getSessionId(), host, port, operatorName, activeSessions.size());
						}

					}
				} catch (IOException e) {
					CONN_LOGGER.error(
							"Attempt {} failed opening connection and bind to {}:{} for operator [{}]. The operator has [{}] active sessions. Error {}",
							attempt, host, port, operatorName, activeSessions.size(), e.getMessage());

					if (sleep < 512) {
						sleep *= 2;
					} else {
						sleep = 1;
					}
					if (!isNormalShutdown) {
						CONN_LOGGER.info("Next reconnect attempt in {} seconds for operator [{}]", sleep, operatorName);
						scheduler.schedule(this, sleep, TimeUnit.SECONDS);
					}

				} catch (InterruptedException e) {
					Thread.currentThread().interrupt();
				} finally {
					sessionBounder.release();
					rlock.unlock();
				}
			}
		};
		scheduler.schedule(r, 1, TimeUnit.SECONDS);

	}

	private SMPPSessionCustom createNewSmppSession() throws IOException {
		final SMPPSessionCustom tmpSession = new SMPPSessionCustom(connectionProperties);
		tmpSession.addSessionStateListener(new SessionStateListenerImpl(5000L));
		final MessageReceiverListener msgReceiverListener = ctx.getBean(MessageReceiverListener.class, operatorName);
		tmpSession.setMessageReceiverListener(msgReceiverListener);
		int timer = connectionProperties.get(ConnectionConstants.OPERATOR_CONNECTION_ENQUIRELINK_TIMER, 10000);
		long timeout = connectionProperties.get(ConnectionConstants.OPERATOR_CONNECTION_ENQUIRELINK_TIMER_TIMEOUT, 6000);
		tmpSession.setEnquireLinkTimer(timer);
		tmpSession.setTransactionTimer(timeout);
		tmpSession.connectAndBind(host, port, bindParameters, 5000);
		return tmpSession;
	}

	@Override
	public boolean isReady() throws InterruptedException {
		return activeSessions.size() > 0;
	}

	/**
	 * Private class SessionStateListenerImpl to make sure automatic
	 * reconnection takes place upon connection loss.
	 * 
	 */
	private class SessionStateListenerImpl implements SessionStateListener {

		private final long reconnectInterval;

		public SessionStateListenerImpl(final long reconnectInterval) {
			this.reconnectInterval = reconnectInterval;
		}

		@Override
		public void onStateChange(SessionState newState, SessionState oldState, Session source) {
			if (newState.equals(SessionState.CLOSED) && !isNormalShutdown) {

				try {
					rlock.lockInterruptibly();
				} catch (InterruptedException e) {

				}
				try {
					activeSessions.remove(source);
					CONN_LOGGER.debug("Session closed for operator [{}]", operatorName);

				} finally {
					rlock.unlock();
				}
				CONN_LOGGER.debug("Active connections left {} for operator [{}]", activeSessions.size(), operatorName);
				reconnectAfter(reconnectInterval);
				source = null;
			}
		}
	}

The ActiveSessions class is:

    public class ActiveSMPPSessions {

	private final static Logger LOGGER = LoggerFactory.getLogger(ActiveSMPPSessions.class);

	private final List<SMPPSessionCustom> activeSessions = new LinkedList<>();

	private Iterator<SMPPSessionCustom> elements = null;

	public synchronized boolean add(final Session session) {
		boolean b = false;
		b = activeSessions.add((SMPPSessionCustom) session);
		createCycle();
		notifyAll();
		return b;
	}

	public synchronized boolean remove(final Session session) {
		boolean b = false;
		b = activeSessions.remove(session);
		createCycle();
		return b;
	}

	public synchronized int size() {
		return activeSessions.size();
	}

	private void createCycle() {
		elements = Iterables.cycle(activeSessions).iterator();
	}

	private void destroyCycle() {
		elements = null;
	}

	public synchronized SMPPSessionCustom getNext() {
		return elements.next();
	}

	public synchronized int indexOf(SMPPSessionCustom session) {
		return activeSessions.indexOf(session);
	}

	public synchronized boolean isAnyBound() {
		return activeSessions.size() > 0;
	}

	public synchronized boolean waitAnyBound() throws InterruptedException {
		while (!isAnyBound())
			wait();
		return true;
	}

	public List<SMPPSessionCustom> getSessions() {
		return new LinkedList<>(activeSessions);
	}

	public synchronized void unbindAndClose() {
		destroyCycle();
		for (final SMPPSessionCustom s : activeSessions) {
			try {
				LOGGER.info("Unbinding and closing of activeSession {}", activeSessions.indexOf(s));
				s.unbindAndClose();
			} catch (Exception e) {
				LOGGER.error("Error unbing session! {}", e.getMessage());
				LOGGER.debug("{}", e);
			}
		}
		activeSessions.clear();
	}

	public synchronized boolean isMaximumConnectedReached(int numberOfSessions) {
		return this.activeSessions.size() >= numberOfSessions;
	}
    }

I should also mention that the SMS are submitted to a threadpool but because each SubmitSM might take up to 36 seconds for the SMSC to respond and in order to achieve 200 TPS I was forced to create 1400 threads (in lack of async capabilities) which I know it can be problematic but had no better solution to it.

The actual sending is done through this callable:

    private class SenderTask implements Callable<SubmitSMResult> {

		private final ShortMessage mt;

		public SenderTask(final ShortMessage mt) {
			this.mt = mt;
		}

		@Override
		public SubmitSMResult call()
				throws PDUException, ResponseTimeoutException, InvalidResponseException, NegativeResponseException, IOException {
			SubmitSMResult sr = null;

			JSMPPMtDTO jsDTO = new JSMPPMtDTO(mt, defaultServiceType, ommitPlusSign);

			scheduleDeliveryTime = relative.format(Date.from(LocalDateTime.now(zoneId).plusSeconds(1).atZone(zoneId).toInstant()));
			validityPeriod = null; // relative.format(Date.from(LocalDateTime.now(zoneId).plusDays(1).atZone(zoneId).toInstant()));
			final SMPPSessionCustom session = activeSessions.getNext();
			LOGGER.trace(
					"Bind Parameters: [ bindType [{}], systemId [{}], password [{}], systemType [{}], addrTon [{}], addrNpi [{}], addressRange [{}]",
					bindType, systemId, password, systemType, addrTon.ordinal(), addrNpi.ordinal(), addressRange);
			LOGGER.trace(
					"Sms [ serviceType: [{}], srcTon: [{}], srcNpi: [{}], sourceAddr: [{}], destAddrTon: [{}], destAddrNpi: [{}], "
							+ "destination: [{}], esmClass: [{}], protocolId: [{}], priorityFlg: [{}], scheduleDeliveryTime: [{}], validityPeriod: [{}],"
							+ " registeredDelivery: [{}], replaceIfPresentFlag: [{}], dataCoding: [{}], smDefaultMsgId: [{}], body: [{}] ].",
					jsDTO.getServiceType(), srcTon.ordinal(), srcNpi.ordinal(), jsDTO.getSender(), destAddrTon.ordinal(),
					destAddrNpi.ordinal(), jsDTO.getDestination(), esmClass, protocolId, priorityFlag, scheduleDeliveryTime, validityPeriod,
					jsDTO.getRegisteredDelivery().value(), replaceIfPresentFlag, jsDTO.getDataCoding(), smDefaultMsgId, jsDTO.getBody());

			final SubmitSmResp submitSmResp = session.submitShortMessageGetResp(jsDTO.getServiceType(), srcTon, srcNpi, jsDTO.getSender(),
					destAddrTon, destAddrNpi, jsDTO.getDestination(), esmClass, protocolId, priorityFlag, scheduleDeliveryTime,
					validityPeriod, jsDTO.getRegisteredDelivery(), replaceIfPresentFlag, jsDTO.getDataCoding(), smDefaultMsgId,
					jsDTO.getBody());

			sr = new SubmitSMResult(mt, submitSmResp);

			return sr;
		}
And the result is handled by Guava's registered callbacks on the Listening service the callable is run by.

**Comment by pmoerenhout** [comment] 2017-01-25 14:01
I just released 2.3.4 where I did remove a synchronized statement when closing. Could you test with this version?

**Comment by alexkonti** [comment] 2017-01-25 14:07
Thank you for your help. Due to the severity of this issue (freezing and most of the times during the night) I switched to cloudhopper. However if I get the chance I will try to test it at a later stage.

**Closed** 2018-06-13 13:29 UTC
